### ISSUE TITLE
Prevent to store in memory all layers

### ISSUE THREAD

**Issue by ChrisCinelli** [wagoodman/dive#105]
On my machine, for large images, the RAM is more a constraint than the CPU.

[The whole layers are copied in memory](https://github.com/wagoodman/dive/blob/8e6709a93a1b10241d96e0f97a680fb2322ef53b/image/image.go#L275-L281).  I tried to fixing this while I was working on #103 .
This is what I did : https://github.com/ChrisCinelli/dive/commit/8e4ea7cb564a273a9937b8ebf47998dc26c68a3f#diff-da07f373046a0a24e67b18699dc15a70  
 but I had to remove the concurrency since the reader is not thread safe. 

By the way,  I also think you have a problem with accessing to the layerMap in processLayerTar at the moment.

**Comment by ChrisCinelli** [comment]
Implemented on: https://github.com/ChrisCinelli/dive/tree/feature/cc/do-not-write-image

**Comment by wagoodman** [comment]
Yeah, this is something like what I had initially without concurrency. I feel that enough bad side effects have been discovered to ditch concurrency (between memory usage and the concurrent hash access) . Feel free to add a PR for this, it would be a very useful fix, @ChrisCinelli !
