### ISSUE TITLE
Avoid having to write on disk the image

### ISSUE THREAD

**Issue by ChrisCinelli** [wagoodman/dive#106]
I worked on fixing this during another PR but it looks like that, even eliminating concurrency, the `tar.Reader` does not behave as I wanted and ended up cutting some bytes.
On the other side when it was working, the initialization was super fast.

**Comment by ChrisCinelli** [comment]
I was actually able to make it work. The code is on https://github.com/ChrisCinelli/dive/tree/feature/cc/do-not-write-image 
Concurrency is off but `dive` loads a lot faster compare to the usual time on my machine and memory consumption is always around 16Mb =)

**Comment by ChrisCinelli** [comment]
Check #106. With the `do-not-write-image` code the laptop is pretty fast and the memory is low.

When I navigate an image with a lot of files, though, `dive` ui is very sluggish. Try with the image `butomo1989/docker-android-x86-9.0`. When you scroll down the layers, you have to eventually wait a few seconds to switch layers. 
The UI code seems to be responsible for this.

**Comment by wagoodman** [comment]
Fixed by #108 , thanks for digging in on this!
