### ISSUE TITLE
Provide `dive` version with `-v` flag

### ISSUE THREAD

**Issue by ccinelli** [wagoodman/dive#109]
```
$ dive
No image argument given
This tool provides a way to discover and explore the contents of a docker image. Additionally the tool estimates
the amount of wasted space and identifies the offending files from the image.

Usage:
  dive [IMAGE] [flags]
  dive [command]

Available Commands:
  build       Builds and analyzes a docker image from a Dockerfile (this is a thin wrapper for the `docker build` command).
  help        Help about any command
  version     print the version number and exit (also --version)

Flags:
      --config string   config file (default is $HOME/.dive.yaml, ~/.config/dive.yaml, or $XDG_CONFIG_HOME/dive.yaml)
  -h, --help            help for dive
  -v, --version         display version number

Use "dive [command] --help" for more information about a command.
$ dive -v
dive No version provided
```

**Comment by wagoodman** [comment]
this only occurs on non-release builds, on release builds it's included:
```
$ ./dive -v
Using config file: /home/wagoodman/.dive.yaml
dive 0.3.0
```
This could probably be enhanced to include git sha and build time as a version stand-in for non-release builds.

**Comment by ccinelli** [comment]
I do not remember how I exactly installed it. I just realized that even if I type `dive` instead of `go run main.go` I do not get the version.

**Comment by willmurphyscode** [comment]
@ccinelli Do you get "No version provided"? That's be behavior that I see. Is there some setup/install step I'm missing?

On macOS:

```
$ go get github.com/wagoodman/dive
$ dive -v
dive No version provided
```

**Comment by wagoodman** [comment]
installing from a `go get` is a non-release build, which simply runs `go build`. A release build is one you download from the github release page (https://github.com/wagoodman/dive/releases)... those are built with 
```
go build -s -w -X main.version=A-VERSION -X main.commit=SOME-COMMIT -X main.buildTime=SOME-TIME`.
```
which overrides these vars: https://github.com/wagoodman/dive/blob/master/main.go#L25-L29
That's configured here: https://github.com/wagoodman/dive/blob/master/.goreleaser.yml#L11

**Comment by ChrisCinelli** [comment]
Ok. I never installed from releases. I am still very new with GO

**Comment by wagoodman** [comment]
Short of hard coding or using `go generate` (which isn't run at `go get` or `go build`) I don't see a way to make this better. I'm open to suggestions (but I'll close for now).
