### ISSUE TITLE
Compute "image efficiency" and display in a stats window. 

### ISSUE THREAD

**Issue by willmurphyscode** [wagoodman/dive#11]
"Efficiency" is basically the property of not having the same information in several different layers.

This metric should indicate what amount of layer overlap there is (in terms of # or files and in total inflated image size). This would give the user an indication that there is room for Dockerfile improvements.

**Comment by wagoodman** [comment]
A portion of this was merged into master, specifically showing the layer efficiency in the layerview. Still need to figure out the best way to show overall stats

**Comment by wagoodman** [comment]
Completed
