### ISSUE TITLE
panic when trying to analyze nonexistent image - error message would have been enough

### ISSUE THREAD

**Issue by leeview** [wagoodman/dive#118]
go version go1.11 windows/amd64

C:\Users\Lee\go\bin>dive sql1
Analyzing Image
Image not available locally. Trying to pull 'sql1'...
Using default tag: latest
Error response from daemon: pull access denied for sql1, repository does not exist or may require 'docker login'
  Fetching metadata...
panic: Error: No such image: sql1

goroutine 1 [running]:
github.com/wagoodman/dive/image.check(...)
        C:/Users/Lee/go/src/github.com/wagoodman/dive/image/image.go:23
github.com/wagoodman/dive/image.getImageReader(0xc0000180d0, 0x4, 0xc0001a3860, 0x1, 0x1)
        C:/Users/Lee/go/src/github.com/wagoodman/dive/image/image.go:271 +0x453
github.com/wagoodman/dive/image.InitializeData(0xc0000180d0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/Lee/go/src/github.com/wagoodman/dive/image/image.go:165 +0x21f
github.com/wagoodman/dive/cmd.analyze(0xdccb60, 0xc000257e30, 0x1, 0x1)
        C:/Users/Lee/go/src/github.com/wagoodman/dive/cmd/analyze.go:36 +0x1b2
github.com/spf13/cobra.(*Command).execute(0xdccb60, 0xc000004430, 0x1, 0x1, 0xdccb60, 0xc000004430)
        C:/Users/Lee/go/src/github.com/spf13/cobra/command.go:766 +0x2d3
github.com/spf13/cobra.(*Command).ExecuteC(0xdccb60, 0x1, 0x1b0000, 0x0)
        C:/Users/Lee/go/src/github.com/spf13/cobra/command.go:852 +0x304
github.com/spf13/cobra.(*Command).Execute(0xdccb60, 0xdccb60, 0xc0001a3f68)
        C:/Users/Lee/go/src/github.com/spf13/cobra/command.go:800 +0x32
github.com/wagoodman/dive/cmd.Execute()
        C:/Users/Lee/go/src/github.com/wagoodman/dive/cmd/root.go:30 +0x38
main.main()
        C:/Users/Lee/go/src/github.com/wagoodman/dive/main.go:38 +0xa9

**Comment by wagoodman** [comment]
fixed in 53b11f4ecf7e42b7896ad518932a22267fbcb23d, should make it in the v0.4.0 release
