### ISSUE TITLE
Option to reverse layers order

### ISSUE THREAD

**Issue by lburgazzoli** [wagoodman/dive#126]
It would be nice to have an option to see the latest layer on top of the layer view. This is useful when dealing with base images and a number of layer are always the same so one can quickly see what has changed.

**Comment by wagoodman** [comment]
I could add an option to reverse the order, though I think it makes more sense to leave the order as is (the same order as the Dockerfile) and add a page-down/page-up ability on the layer view. In this way you could very quickly jump to the last layer. I could also make the view "circular" such that when you arrow up on the top layer, it jumps to the last layer (possibly disorienting, but I feel that would be better than reversing the order).

**Comment by lburgazzoli** [comment]
Both are fine with me

**Comment by wagoodman** [comment]
Added pgup/pgdown key options in 184d3a2b0c82d149f17e17c6494d3a4e4a1f93c8 , should be in the v0.7.0 release
