### ISSUE TITLE
Keybindings library

### ISSUE THREAD

**Issue by glvr182** [wagoodman/dive#134]
Hey after going through the source I noticed the keybindings file basicly translates it into keys. 
Would it be possible to make a library out of that, since I would love to use it in my own apps.

**Comment by wagoodman** [comment]
@glvr182 I ported the functionality to https://github.com/wagoodman/keybinding which I'll switch dive over to in the next release. I haven't done much with it, it needs a few more tests, and I'm open to extending functionality. Shout out if you make something cool with it :)

**Comment by glvr182** [comment]
Legend! I'll let you know!
