### ISSUE TITLE
FTBFS with go 1.11.4, please regenerate go.sum 

### ISSUE THREAD

**Issue by CameronNemo** [wagoodman/dive#137]
go 1.11.4 fixes a bug where the checksums for certain types of go modules are incorrectly generated.

To workaround this, you must regenerate the go.sum file. You likely need to run `go clean -modcache` before deleting and regenerating the checksums file.

See the following issues for more information:

https://github.com/golang/go/issues/29278

https://github.com/golang/go/issues/29282

**Comment by wagoodman** [comment]
thanks for the heads up. I haven't been able to reproduce, but I did regenerate based off of the 1.11.4 bug fix. Let me know if this does the trick for you... if not feel free to reopen this ticket and we can investigate.

**Comment by CameronNemo** [comment]
Thanks for the quick response, the updated checksums worked perfectly.
