### ISSUE TITLE
control key suggestions

### ISSUE THREAD

**Issue by robbuckley** [wagoodman/dive#151]
first, thanks for a great tool! A couple of things I noticed, and suggestions for control key changes:

- filtering out modified files (^M) tends to turn off entire directory trees, unless the whole tree has been added or removed in the same layer. This makes much less useful than it could be, since almost every top level folder with some added / deleted files will be marked as modified, and hidden. It might be more useful to only filter out subtrees if every file in the subtree is modified

- a key to reset all the collapsed folders (eg ESC) could be handy

**Comment by wagoodman** [comment]
The modification issue has been resolved (https://github.com/wagoodman/dive/compare/modified-dir-fix?expand=1#diff-9c8e53abc09c6994b1013b2810967df5R516)
