### ISSUE TITLE
Stuck on "Fetching image"

### ISSUE THREAD

**Issue by vilhelmen** [wagoodman/dive#153]
Is there a way to skip image fetch? Dive has been getting stuck trying to fetch the image I already have downloaded and I have to kill it and restart docker (docker activity spikes and won't go back down). Is dive somehow triggering a full download even though the image already exists locally?

This only seems to happen to images in our private registry (a GitLab EE server). They're largish (6GB UGH), but I already have the latest version downloaded when I run dive. I enabled debug logging, but all it says is `level=debug msg="Starting Dive..."`

I'm on MacOS 10.14.2, Docker for Mac Version 2.0.0.2 (30215), engine 18.09.1, dive 0.6.0 installed via homebrew.

**Comment by wagoodman** [comment]
The 'fetching image' step probably should get renamed. Dive is exporting the image as a tar file from docker similar to the `docker image save ...` command. In this way it can parse each layer as file-system changes. So 'fetching' in this case just means 'export from the API', not 'download it from the registry'. There isn't a nice (and portable) way to avoid this unfortunately. 

I've been analyzing images as large as 10 GB, though it takes a while (sometimes up to a minute) to get the full image exported. You are seeing spikes in docker activity, are you noticing a shortage of available memory too?

It may be advantageous to allow for dive to be given a tar of the image by the user, in that way the fetch step can be avoided entirely (making the user run `docker image save ...` manually)

**Comment by wagoodman** [comment]
Sounds good. I updated the fetching image step to note that is may take a while.

**Comment by jithunnair-amd** [comment]
I second this: "The 'fetching image' step probably should get renamed." It does give the wrong impression that it's re-downloading the image.

**Comment by jermwatt** [comment]
I third this: when I saw "fetching image" I imagined the image was being re-downloaded.
