### ISSUE TITLE
any option to disable loader  for CI?

### ISSUE THREAD

**Issue by thib3113** [wagoodman/dive#157]
is an option existing to disable very loud progress bar, maybe a `--quiet` option ?

In my CI process, dive output more than 600 lines, about progress bars . 

I've activated the CI env Var .

**Comment by wagoodman** [comment]
Not yet, but I agree that the output should be less verbose in CI mode

**Comment by wagoodman** [comment]
The loading/parsing progress output wasn't adding a lot of value, so I removed it in ab3bbb8735d668b485b40853cf967792dfc15123  .

**Comment by thib3113** [comment]
@wagoodman I thinks it's add some value for better user friendly UI (just to be sûre something is running, and not juste wait infinite loop). But not for CI use . I thinks removing all is maybe not the good idea, just disabling it for CI ( or to be faster disabling it for the moment ) . In each case, your code is in git .

**Comment by wagoodman** [comment]
I agree overall with what you're saying: having a UI show progress on a task is helpful. I was originally going to disable it for just the CI case, but after further thought, the progress bars weren't really the majority of the process. 

Of the few steps (fetching, parsing, analyzing, and building cache) only the parsing step showed the progress bars (one for each layer). However for the vast majority of images (including large images) the parsing step is very fast, usually sub second, sometimes a couple seconds. Additionally, the progress bars were showing the time to iterate files in each layer, but weren't showing progress for the expensive step in the process (https://github.com/wagoodman/dive/commit/ab3bbb8735d668b485b40853cf967792dfc15123#diff-ca5f656ad45d5dcb229b31cd7c7ea87dR197). This lead to the progress bars always showing either 0% or 100%, but not much in between ever. This also made more sense when I was processing each layer in parallel, which is no longer the case (tar reader limitation).

Also, this is just one step in the 4 steps where work is being done. The most expensive step is the "fetch" step done first, which never had any progress shown (I really wanted to be able to do that, but it seems to be a docker-specific limitation). As a result, it didn't make much sense to enhance the output that was being verbose... so I instead opted to remove it. 

The titles of each of the 4 sections being processed is still output to the screen, but until there is a better way to interrogate the progress made within each step there isn't much reason to display more.

**Comment by AubreySLavigne** [comment]
I'm glad to hear the parsing loader is removed. I was actually going to recommend the same for exactly that reason -- it's just too fast to be useful.

If anything, the progress bar should be displayed on a "per-layer" basis, rather than a "per-file" basis, as that's happening in a much more human-scale time.
