### ISSUE TITLE
Compare Bar changes for Layers View

### ISSUE THREAD

**Issue by AubreySLavigne** [wagoodman/dive#164]
I'd like to suggest two related changes for the compare bar on the left side of the Layers view.

* In `CompareLayer` mode, I'd recommend the "bottom" range for the compare bar visual (on the left) to only select the previous layer. For example:

![image](https://user-images.githubusercontent.com/10681468/53071647-cd042480-34b0-11e9-9579-00bd2c7e65f0.png)

* In `CompareAll` mode, it makes sense to be able to compare changes in a selected range, rather than always having the bottom range start at index 0. For example:

![image](https://user-images.githubusercontent.com/10681468/53071806-4b60c680-34b1-11e9-8be3-73bca6c68e65.png)

**Comment by AubreySLavigne** [comment]
I've already made these changes, wanted to know if this made sense to you first.

**Comment by wagoodman** [comment]
Just for a reference point about the compare bar visual: it depicts one stack vs another stack, where a stack is one or more layers combined into a single tree. The purple tree being compared against the green tree to generate the filetree in the right pane.

1. For CompareLayer , the mock up you provided indicates that the green tree is comprised of a single layer (layer 5). However, when the comparison is done in reality the green tree is comprised of a combination of layers 1-5 and then compared to the purple tree made of 1 layer (layer 6). However, I do see how this is visually more enticing, as there is a better contrast from "compare all" to "compare layer", but I think it's also visually inaccurate to what the comparison is actually doing.
 
2. I've been wanting to add the ability to select a different lower bound layer for the green tree for a while now, so I'm all for it! The biggest problem has been making an intuitive control/keybinding to manipulate the lower bound layer. Do you have an interaction in mind? (Also, I think this could be valid for the compare layer mode too, though awkward to find a particularly useful use case)

Just an FYI, I'm in the midst of a fairly sizable refactor to make the filetree ui component more testable. I'm hoping to get the PR up tonight or tomorrow, but if you wanted to open a PR I'd branch off of the `add-testable-viewmodels` branch in the meantime (or hold off a day)... pardon my dust.

**Comment by AubreySLavigne** [comment]
The majority of these changes are to the ui.getCompareIndexes function, so the comparison is accurate to what is being displayed.

1. For the CompareLayer mode, could you explain a bit more what the different between [1-5:6] and [5:6] would be? The way I currently understand it, the two appear to be equivalent, because the delta between the two layers is really defined by layer 6. This particular change was based on this understanding.

1. For the CompareAll mode, the method I am using is to change CompareStartIndex to (LayerIndex - 1) when entering that mode by hitting `^A` (by contrast, CompareStartIndex is ignored in CompareLayer mode). I personally found this intuitive, but changing it from there might need to have a different method -- Personally, I just switch back to CompareLayer mode and back to CompareAll to refresh.  Also, my current version does allow you to set the topTree below the bottomTree, which is one reason I've held off on creating the PR yet.

**Comment by wagoodman** [comment]
1. You're right, the layer already represents the diff to be applied (so there is no difference between [1-5:6] and [5:6]). Wouldn't the right visual then be no comparison? (just show the purple block with no green block). 
2. The keybindings are fairly limited (https://github.com/jroimartin/gocui/blob/master/keybinding.go#L47-L127) I would like to do something like shift+arrow keys will move the bottom layer (and arrow keys would do the same thing they do today, move the top layer), I don't think this is possible with gocui, but haven't dived far enough to see if there is a workaround either.

**Comment by wagoodman** [comment]
@AubreySLavigne you still interested in implementing this issue? (not rushing you, just curious)

**Comment by AubreySLavigne** [comment]
I'm sorry for not replying. I will close out this issue so it's not on your backlog any more.
