### ISSUE TITLE
Windows package management with scoop

### ISSUE THREAD

**Issue by patrick330602** [wagoodman/dive#166]
It would be pretty nice if `dive` can be included in [Scoop](https://scoop.sh), which is a command line package management system for Windows, for easier install and upgrades. 

I have already tried to make [one](https://github.com/patrick330602/pkscbk/blob/master/dive.json) and it is working properly with Scoop. I didn't release it to the Main bucket as I hope to get some comments from the author. DO you think this would be a good idea?

**Comment by craigktreasure** [comment]
I realize this issue is somewhat old, but `dive` is now available in the main Scoop bucket. This can likely be closed.
