### ISSUE TITLE
Correct config file location in README.md

### ISSUE THREAD

**Issue by akshaychhajed** [wagoodman/dive#170]
`~/.config/dive.yaml` is incorrectly listed. 
Config is searched in `~/.config/dive/*.yaml`

**Comment by Sarke** [comment]
The readme is correct for the current release `0.6.0`, see https://github.com/wagoodman/dive/pull/159#issuecomment-464989285

**Comment by wagoodman** [comment]
(I'll make certain to merge closer to the next release)

**Comment by akshaychhajed** [comment]
Going through #159 gives a clear picture. Thanks @Sarke
