### ISSUE TITLE
Can't scroll

### ISSUE THREAD

**Issue by revolter** [wagoodman/dive#185]
If I collapse all dirs of set the respective preference in a config file, I can't scroll down in the right pane using the down arrow key.

**Comment by AlexFalappa** [comment]
I am experiencing this too.
Collapsing some folders in the file tree reduces the range of scrolling i.e. pressing the down arrow keys does not reach the bottom.
With all the folders expanded you can actually scroll one position below the bottom.

**Comment by revolter** [comment]
I can't even go down from the first folders, even though there is a lot of content underneath.

**Comment by delabassee** [comment]
I am observing the following on 0.7.1 :
- ctrl-space to 'collapse all' :  ⬇️ key binding doesn't work (⬆️ works fine!)
- collapse dirs indivudually one by one : both ⬇️ and ⬆️ bindings works fine.

**Comment by shoelzle** [comment]
I'm experiencing the same issue with dive 0.7.1.

**Comment by wagoodman** [comment]
Thanks for reporting, @revolter (+ et. al.). Looks like there was an issue in considering collapsed directories while traversing the tree. This fix has been incorporated in release v0.7.2.
