### ISSUE TITLE
Windows downloaded file locations

### ISSUE THREAD

**Issue by DooDiddle** [wagoodman/dive#192]
I ran this under windows. It downloaded the docker image then did some other things. Where does it store temporary and downloaded files so I can remove them so they don't fill up my disk?

**Comment by wagoodman** [comment]
Dive is fetching the image (a tar file containing the image layer contents) from the docker daemon via the `ImageSave` feature. On the CLI, the `docker save ...` command saves the output to disk, however, dive does not do this. Instead the tar is immediately processed as it is streamed in from the docker daemon, not saving the contents of the layers anywhere to disk. So there should be no need to purge any files (as they are not persisted anywhere). If you're interested, that behavior is implemented here: https://github.com/wagoodman/dive/blob/65f87b00a947a20dc62f57cfef1c59009ba2fec2/image/docker_image.go#L116

Let me know if you have any questions.

**Comment by wagoodman** [comment]
Since this isn't a bug or feature request, I'll close it for now. Feel free to comment or reopen this issue if you feel that there is a problem.
