### ISSUE TITLE
Add command line options to improve running CI directly from wagoodman/dive Docker image

### ISSUE THREAD

**Issue by ianfixes** [wagoodman/dive#198]
If you have `dive` installed locally, there is no issue here.  But if you want to run `dive` directly from the `wagoodman/dive` container, it's a little bit clunky to specify the environment variables and config files.  It can be done like this:

```shell
$ docker run --rm -i -v /var/run/docker.sock:/var/run/docker.sock \
  -e CI=true wagoodman/dive:latest \
  IMAGE_UNDER_TEST \
  --ci-config /dev/stdin < DIVE_CONFIG.YML
```

If your CI runs commands directly (without a shell), you have to wrap the whole thing in `sh -c 'docker run ... < DIVE_CONFIG.YML'` to get the redirect to work.  So it would be nicer if I could just specify the 4 available parameters directly on the command line:

* `--ci` to replace the `CI=true` environment variable
* Individual items to replace `--ci-config`
    * `--lowestEfficiency`
    * `--highestWastedBytes`
    * `--highestUserWastedPercent`

Then, the command could look like this, with no need to wrap in `sh -c`:

```shell
$ docker run --rm -i -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive:latest \
  IMAGE_UNDER_TEST \
  --ci \
  --lowestEfficiency 0.95 \
  --highestWastedBytes 20MB \
  --highestUserWastedPercent 0.20
```

**Comment by wagoodman** [comment]
Look for this change in the upcoming v0.8.0 release

**Comment by ianfixes** [comment]
Awesome, thank you!
