### ISSUE TITLE
Error: cannot fetch image: cannot find docker client executable

### ISSUE THREAD

**Issue by jfisbein** [wagoodman/dive#240]
I'm running this command in ubuntu 18.04:
```
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive:latest mongo
Fetching image... (this can take a while with large images)
cannot fetch image: cannot find docker client executable
```
Dive version:
```
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive:latest --version
dive 0.8.1
```
Docker version
```
docker --version
Docker version 19.03.4, build 9013bf583a
```

This worked some time ago, and now it stopped working.

**Comment by wagoodman** [comment]
I've just cut a new release (v0.9.0) which should fix the error you are seeing. This new release is using the debian base image to simplify the new podman addition --the downside is that the image will be larger than the last release.

**Comment by jfisbein** [comment]
Thanks it worked!
