### ISSUE TITLE
Does not run on RHEL7/CentOS 7 anymore (regression)

### ISSUE THREAD

**Issue by Nindaleth** [wagoodman/dive#248]
Dive 0.9.0 does not work on RHEL 7 anymore; 0.8.1 does.

The required libc version has increased from nothing to 2.28:
```
$ rpm -qRp dive_0.9.0_linux_amd64.rpm | grep GLIBC
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.28)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libpthread.so.0(GLIBC_2.12)(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
libpthread.so.0(GLIBC_2.3.2)(64bit)
librt.so.1(GLIBC_2.2.5)(64bit)

$ rpm -qRp dive_0.8.1_linux_amd64.rpm | grep GLIBC
```

While the glibc I have on my up-to-date system is this:
```
$ rpm -q glibc
glibc-2.17-292.el7.x86_64
```

I noticed the change in building procedure and I don't mind downloading a bigger package that much, but please consider "old" distributions such as RHEL7 (we don't have RHEL8 VMs available yet where I work). For reference, that RHEL7 provides docker 1.13.1, while RHEL6 provides glibc-2.12 and docker 1.5.

Dive 0.8.1 works just fine and is what I use for now.

**Comment by wagoodman** [comment]
Indeed, 0.9.0 was straight up broken in several ways. I've since released 0.9.1 which fixes the dependency issues you are seeing. Would you mind trying again to see if this fixes your problem?

I'll be adding a step in the pipeline to check for testing package installation and such in the (very) near future.

**Comment by Nindaleth** [comment]
Yup, the installation (and binary) now works again. Thanks for the quick fix!

**Comment by 1138-4EB** [comment]
@wagoodman, @Nindaleth, should this be closed?
