### ISSUE TITLE
Failed to go get on Debian

### ISSUE THREAD

**Issue by afritzler** [wagoodman/dive#257]
Installing via
```
go get github.com/wagoodman/dive
```

results in the following error
```
$ go get github.com/wagoodman/dive

# github.com/wagoodman/dive/dive/image/docker
go/pkg/mod/github.com/wagoodman/dive@v0.9.1/dive/image/docker/engine_resolver.go:53:19: undefined: client.Opt
go/pkg/mod/github.com/wagoodman/dive@v0.9.1/dive/image/docker/engine_resolver.go:81:34: undefined: client.WithAPIVersionNegotiation
```
Environment:
* ChromeOS Linux Env (Debian 9)
* Go lang: go1.13.4 linux/amd64

**Comment by eine** [comment]
Cannot reproduce in a docker container:

```sh
docker run --rm debian:stretch-slim bash -c "
apt update -qq
apt install -y git curl
curl -fsSL https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz | tar xzf - -C /usr/local/
export PATH=\$PATH:/usr/local/go/bin
go get -v github.com/wagoodman/dive
"
```

**Comment by afritzler** [comment]
Thanks for digging into this @eine. Looks like I had to `unset GO111MODULES` on my box to make this work. 🙈 Closing.

**Comment by cben** [comment]
Same on Fedora 30, go1.13.5.  This worked (no it's GO111MODULE not GO111MODULES), not sure why as this project does have a `go.mod` & `go.sum` :shrug: : 
```sh
env GO111MODULE=off go get -v github.com/wagoodman/dive
```

**Comment by cben** [comment]
Aha, got it.  I happened to be running the `go get github.com/wagoodman/dive` _inside another go project_ directory.  
That was interpretted as "add a depedency to the containing project", messed with my go.mod & go.sum, and got conflicts.  Using GO111MODULE=off didn't touch my project, but that's a silly fix, the real fix is run `go get` outside any go projects (say from the home dir).
