### ISSUE TITLE
Save results as environment variables 

### ISSUE THREAD

**Issue by hilsenrat** [wagoodman/dive#260]
Hi,
I discovered this tool today and I'd like to implement it in our projects.
I'd like to have the option to display the main scores (image efficiency and wastedBytes) in Jenkins.
There is the option to parse the output, but getting the from the env vars will be much more ideal.
Please let me know if I can contribute to the development effort to this great project.
Thanks.

**Comment by wagoodman** [comment]
I agree, parsing the terminal output would be tedious, so I recently added an option to allow for json output to a file:
```bash
dive your-image:latest --json a-file.json
```
which will output a listing of the layers, as well as the analysis results:
```
{
  "layer": [
    {
      "index": 0,
      "id": "ea96e16ec7df50909a98f23dc3cc1b3ecc14a5d20892d21a1e3899b3bb06f237",
      "digestId": "sha256:1da8e4c8d30765bea127dc2f11a17bc723b59480f4ab5292edb00eb8eb1d96b1",
      "sizeBytes": 1219790,
      "command": "#(nop) ADD file:1141b81e5149cc37c4346ee17e282cca8c7016a9bcfeb7a54842a87ecf8419d4 in / "
    },
    {
      "index": 1,
      "id": "d9a38b0599d4f0c18d18c648ad7c5eedc2724d1c14e713426931e3aaea30b26b",
      "digestId": "sha256:f5454c7b2ff967556965a07d57176b4bfb21a15ee17a17ff845bf3a4034fb2b7",
      "sizeBytes": 8912,
      "command": "#(nop) ADD file:624d04440aafeb722b5b8dc10334b8edbe0db376e786bb140fe1530c279f7225 in /somefile.txt "
    },
    {
      "index": 2,
      "id": "b8d4bfb12d888fc6521390d7e98f35667d5fd240a1ea78c563f9352cc110f700",
      "digestId": "sha256:299b52d879fbeba378dd6e7f2771d06256c65b959caa7cf20e33518ad61d9bfa",
      "sizeBytes": 0,
      "command": "mkdir -p /root/example/really/nested"
    },
...
<snip>
...
    {
      "index": 14,
      "id": "b49ecbec0b8c0e4b10639160055afbf5f079a53cf43a5f93fc94b2b48282b87e",
      "digestId": "sha256:6bd858f2a4d68ca6bde9eb2f241a63acdd8a9ebbdb364ee716734e82220a6535",
      "sizeBytes": 0,
      "command": "chmod 421 /root"
    }
  ],
  "image": {
    "sizeBytes": 1311097,
    "inefficientBytes": 44560,
    "efficiencyScore": 0.9798814225977316,
    "fileReference": [
      {
        "count": 2,
        "sizeBytes": 17824,
        "file": "/root/saved.txt"
      },
      {
        "count": 2,
        "sizeBytes": 17824,
        "file": "/root/example/somefile1.txt"
      },
      {
        "count": 2,
        "sizeBytes": 8912,
        "file": "/root/example/somefile3.txt"
      },
      {
        "count": 2,
        "sizeBytes": 0,
        "file": "/root"
      }
    ]
  }
}
```
And the two fields you're interested in are `.image.efficiencyScore` and `.image.inefficientBytes`. 

If you'd like to extract these values individually, I'd recommend using a tool like jq:
```bash
$ dive your-image:latest --json dive-result.json 
...

$ cat dive-result.json  | jq '.image.sizeBytes,.image.efficiencyScore'
1311097
0.9798814225977316
```

Since you're using Jenkins, you can archive the entire result with the `archiveArtifacts` dsl (see https://jenkins.io/doc/pipeline/tour/tests-and-artifacts/).

Regarding your request for injecting the results as environment variables, I don't think there is a [kosher] way to add/modify environment variables for the parent process. However, given the above info, I don't think that is needed. 

Let me know if you have any questions or have a more specific example for the env var use case.

**Comment by hilsenrat** [comment]
Thanks @wagoodman 
The option to get output in JSON is great. I added the following commands to my shared libraries and now I'm archiving the dive results per each built image and can see the image size and efficiency in the Build History view.

`def call(Map config = [:]) {

    def publishTag = config.publishTag

    // Getting diveConfig from shared lib
    def diveConfigText = libraryResource 'dive/.dive-ci'
    def diveConfigName = '.dive-ci'
    def diveJSONResult = 'dive-output.json'
    writeFile file: "${diveConfigName}", text: "${diveConfigText}"

    // Running dive command
    def diveCommand = "CI=true dive ${publishTag} --config ${diveConfigName} --json ${diveJSONResult}"
    sh diveCommand
    
    // Calcaulating Dive results
    def imageSizeBytes = sh(returnStdout: true, script: "cat ${diveJSONResult} | jq '.image.sizeBytes'").trim().toLong()
    def imageSizeMB = imageSizeBytes.intdiv(1024).intdiv(1024)
    def imageEfficiencyScore = sh(returnStdout: true, script: "cat ${diveJSONResult} | jq '.image.efficiencyScore'").trim().toDouble()
    int imageEfficiencyPercentage = imageEfficiencyScore * 100
    
    // Setting Build descritpion with Dive values
    currentBuild.description = !currentBuild.description?.trim() ? "Image Size: ${imageSizeMB}MB" : "${currentBuild.description}\nImage Size: ${imageSizeMB}MB"
    currentBuild.description = !currentBuild.description?.trim() ? "Image Efficiency: ${imageEfficiencyPercentage}%" : "${currentBuild.description}\nImage Efficiency: ${imageEfficiencyPercentage}%"
    
    // Archiving dive results
    archiveArtifacts "${diveJSONResult}"
}
`
