### ISSUE TITLE
How to find "Potential wasted space" files 

### ISSUE THREAD

**Issue by LeeJian** [wagoodman/dive#264]
Total Image size: 4.4 GB
Potential wasted space: 274 MB
Image efficiency score: 96 %

How to find that 274 MB files?

[Image Details] failed to show all information due to the big image, have to use smaller font to see more lines.

**Comment by wagoodman** [comment]
You can get this information via the `--json` option to output results to a file, including a list of "inefficient files". In the future there will probably be UI adjustments to allow for scrolling in the details pane (or or similar solution).
