### ISSUE TITLE
--ls option to list image contents to stdout

### ISSUE THREAD

**Issue by abitrolly** [wagoodman/dive#270]
I am trying to index some popular images on Docker Hub - https://devops.stackexchange.com/questions/10192/find-most-popular-images-with-zip-and-git-on-docker-hub - and it could help if `dive` was able to dump list of files to stdout.

**Comment by wagoodman** [comment]
Short answer is that dive does not do this. However, if you have the image dive isn't needed to do this:
```
# list all files in a new container, which should only be what is in the image
docker --rm <some-image>:latest find /
```
I also posted (half) an answer back on your [stackexchange](https://devops.stackexchange.com/questions/10192/find-most-popular-images-with-zip-and-git-on-docker-hub/10754#10754). I suspect anything you find will need to crawl a registry and index files within images manually or find a service that is already doing this on each push.

**Comment by abitrolly** [comment]
That requires `bash` and `find` to be present in the image, which is not always `true`.
