### ISSUE TITLE
Failed to write to log, invalid argument

### ISSUE THREAD

**Issue by CurryWurry** [wagoodman/dive#271]
W10
dive version 0.9.1

Hi, 
I'm getting the above error when using dive on W10, installed locally + running from docker:
Fetching image... (this can take a while for large images)
Analyzing image...
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Building cache...
Failed to write to log, invalid argument
cannot build cache tree
Failed to write to log, invalid argument
cannot remove upperNode /var/lib/yum/rpmdb-indexes/conflicts: path does not exist: /var/lib/yum/rpmdb-indexes/conflicts

The image I tested on is big (that's why we want to use dive), it works with a few smaller images.

**Comment by finkr** [comment]
I have the same issue. it works fine with  v0.8.1

**Comment by CurryWurry** [comment]
> 
> 
> I have the same issue. it works fine with v0.8.1

tx for pointing me to that version, v0.8.1 indeed works. I see the same "failed to write to log" messages however, but at least it's no longer a blocker

**Comment by bormm** [comment]
I have the same issue on Windows 10 Version 1903 using docker desktop 2.1.0.5 and dive 0.9.1

**Comment by abitrolly** [comment]
Can you compile `dive` from source and make a `git bisec` to find offending commit?

**Comment by wagoodman** [comment]
Thanks for reporting, I added more aggressive error checking when parsing images around ~v0.9.0, but since v0.9.2 (released today) have compromised on this. A few suggestions:
- Try out v0.9.2, let me know if it works or not!
- If 0.9.2 doens't work, and you have a public image (or a Dockerfile facsimile), can you let me know the image?

**Comment by keeganwitt** [comment]
0.9.2 fixed the issue for me.
