### ISSUE TITLE
dive build fails with Server did not provide an image ID

### ISSUE THREAD

**Issue by finkr** [wagoodman/dive#272]
When I try to run **`dive build`** in the docker.io/wagoodman/dive container, I get the errors:

## Error:

    Server did not provide an image ID. Cannot write /tmp/dive.360495168.iid
    cannot build image
    Failed to write to log, invalid argument

Building the image with docker within that image works.

## Step to reproduce

Create a Dockerfile:

    mkdir /tmp/dive
    cd /tmp/dive
    echo "FROM library/busybox" >Dockerfile
    RUN echo test > /tmp/test   >> Dockerfile

Then run:

     docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$(pwd)":"$(pwd)"   -w "$(pwd)" -ti  wagoodman/dive build -t foo/bar:latest .

**The execution log:**

```
Building image...
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM library/busybox
 ---> b534869c81f0
Step 2/2 : RUN echo test > /tmp/test
 ---> Running in a71f209bffb1

 ---> b73a73978ae0
Removing intermediate container a71f209bffb1
Successfully built b73a73978ae0
Server did not provide an image ID. Cannot write /tmp/dive.501940426.iid
cannot build image
Failed to write to log, invalid argument
exit status 1
```

Note that the image is created:

    $ docker images foo/bar:latest
    REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
    foo/bar             latest              b73a73978ae0        18 seconds ago      1.22 MB

## versions used:

**dive**
```
$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock --entrypoint= -ti  wagoodman/dive dive -v
dive 0.9.1
```

**docker**
```
# docker run --rm -v /var/run/docker.sock:/var/run/docker.sock --entrypoint= -ti  wagoodman/dive docker version

Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.26 (downgraded from 1.40)
 Go version:        go1.12.5
 Git commit:        74b1e89e8a
 Built:             Thu Jul 25 21:17:37 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          1.13.1
  API version:      1.26 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       7f2769b/1.13.1
  Built:            Fri Aug  2 10:19:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by finkr** [comment]
dive needs docker argument `--iidfile FILE`, which was introduced in [v17.06.0-ce](https://github.com/docker/docker-ce/releases/tag/v17.06.0-ce)

**Comment by wagoodman** [comment]
Yeah, unfortunately the Docker version you're using is too old (`1.13.1`), and as you mentioned, the feature in question is just a few releases after the version you're using. 

A workaround would be to run `docker build <image>` followed by `dive <image>`, which should work fine. Shout out if that does the trick!
