### ISSUE TITLE
Support Jib Images

### ISSUE THREAD

**Issue by Xaseron** [wagoodman/dive#276]
I'm currently trying out jib https://github.com/GoogleContainerTools/jib and dive currently fails to open an image made by jib:
```
Fetching image... (this can take a while for large images)
Analyzing image...
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Building cache...
Failed to write to log, invalid argument
cannot build cache tree
Failed to write to log, invalid argument
cannot remove upperNode /var/log/anaconda: path does not exist: /var/log/anaconda
```

**Comment by wagoodman** [comment]
Actually, Docker images built by jib should already be supported. Can you provide more information to help with the investigation?
- What OS are you running on?
- What version of dive are you using? (and try the latest to see if you have better luck)
- Turn on debug logs and post the output here:
```yaml
# config.yaml
log:
  enabled: true
  path: ./dive.log
  level: debug
```
Then run with `dive --config config.yaml <your image>` and you should see a `dive.log` after the output.

Thanks!

**Comment by Xaseron** [comment]
Awesome, it works flaweless now. 👍 
i've build the image with `gradle jibBuildTar` and imported the image with `docker load --input`.
