### ISSUE TITLE
Error `open /home/wagoodman/Downloads/image/image.tar: no such file or directory`

### ISSUE THREAD

**Issue by mwidmann** [wagoodman/dive#28]
I find this tool very cool, but I'm getting this error if I try to dive into a docker image:

```
❯ dive jenkins/jenkins
Analyzing Image
Using default tag: latest
latest: Pulling from jenkins/jenkins
Digest: sha256:5d9450a3b391e96a1525f6a5b40b3e2095df7a19195b6341fb097120cb0ab099
Status: Image is up to date for jenkins/jenkins:latest
open /home/wagoodman/Downloads/image/image.tar: no such file or directory
```

I installed the deb package 0.0.4 the way you stated in the Readme.

**Comment by wagoodman** [comment]
I just removed the debug code causing this problem and pushed a new version (0.0.5), thanks for reporting @mwidmann
