### ISSUE TITLE
Dive RPM package doesn't include a description

### ISSUE THREAD

**Issue by dereckson** [wagoodman/dive#280]
Hello,

I've included the Dive package in the repository used on my CentOS servers, and it seems the package doesn't include a description:

```
$ dnf search dive
Last metadata expiration check: 0:02:53 ago on Sat 15 Feb 2020 06:26:14 AM UTC.
=============================== Name Exactly Matched: dive ===============================
dive.x86_64 : no description given
```

The package manifest doesn't seem to contain a description, could you check if you include a line like `Summary: Explore each layer in a docker image`  in the package SPEC file?

Reference for Summary: https://rpm-packaging-guide.github.io/ (this page provides a sample .spec file with the useful fields for metadata + tables explaining the options)

**Comment by abitrolly** [comment]
@dereckson `dive` uses https://github.com/goreleaser/goreleaser You can try to read where it expects the summary field to be found.

**Comment by dereckson** [comment]
https://carlosbecker.com/posts/nfpm/ - Description in nfpm.Info it seems.

**Comment by abitrolly** [comment]
Probably you just need to add it to appropriate section of `.goreleaser.yml`- https://github.com/wagoodman/dive/pull/244/files
