### ISSUE TITLE
Layers selection area pushes other UI elements offscreen

### ISSUE THREAD

**Issue by dundir** [wagoodman/dive#285]
I recently tried this application out with a docker image containing 32 layers. 

The Image and Layer Details portion of the screen ends up being cut off at the bottom of the screen making the details unreadable.

**Comment by summea** [comment]
I think this type of situation happens for me as well for an image that has many layers (e.g., more than 40).

**Comment by wagoodman** [comment]
Implemented in https://github.com/wagoodman/dive/pull/399
