### ISSUE TITLE
Support Ctrl-Z for job control.

### ISSUE THREAD

**Issue by Ferada** [wagoodman/dive#297]
It looks to me like pressing <kbd>Ctrl-Z</kbd> does nothing, when in fact that should pause the process. Would it be possible to have that going to the shell instead of capturing all keypresses? The same issue is with <kbd>Ctrl-L</kbd> which should ideally refresh the screen (why's that a good idea to have? because sometimes you end up with a garbled terminal because some other process is still writing there; right now you'd have to restart to be back in a consistent and usable state).

**Comment by tonymet** [comment]
i can take this one

**Comment by tonymet** [comment]
in the meantime i suggest  `tmux`. i had the same issue.

**Comment by yurenchen000** [comment]
3 years later, 
did anyone implement it?

**Comment by tonymet** [comment]
> 3 years later, did anyone implement it?
I remember attempting it for a couple days.  There was an issue with resetting the tty that I couldn't get around. I tried sending reset control codes to the tty. 

ctrl-Z / SIG-STOP worked, but SIG-RUN would restore the app to a broken state on the tty.  no input could be received and screen was blank.

**Comment by yurenchen000** [comment]
> ctrl-Z / SIG-STOP worked, but SIG-RUN would restore the app to a broken state on the tty. no input could be received and screen was blank.

still same reaction
seems dive didn't handle those signal rightly

**Comment by yurenchen000** [comment]
@tonymet @Ferada 
I have send a PR for the feature

**Comment by yurenchen000** [comment]
people maybe also interest in 

`gdu ctrl+z support`[^1]

[^1]: https://github.com/dundee/gdu/issues/249
