### ISSUE TITLE
Support non-docker

### ISSUE THREAD

**Issue by zendril** [wagoodman/dive#299]
Most of our CI are running on systems where either:
- Docker isn't installed or allowed (because it would open up docker in docker and thus need the sock open)
- Docker sock is disabled
- Running in kubernetes where it isn't using docker

Is it possible to shift to a set of libraries that can pull the images and layers without needing docker?

**Comment by wagoodman** [comment]
Indeed! `dive` already supports opening a tarball, so combining this with `skopeo` you should be good to go:

```bash
❯ skopeo copy docker://docker.io/centos:8 docker-archive:centos-8.tar
Getting image source signatures
Copying blob 8a29a15cefae done  
Copying config 470671670c done  
Writing manifest to image destination
Storing signatures
❯ dive docker-archive://centos-8.tar
```

(If this didn't resolve your issue feel free to repoen)

**Comment by lacek** [comment]
What is the supported docker version?

I've got a pretty old system with Docker 1.6.2 and it run into error with:

```
$ docker save -o centos-8.tar centos:8
$ dive docker-archive://centos-8.tar
Image Source: docker-archive://centos-8.tar
Fetching image... (this can take a while for large images)
cannot fetch image
could not find image manifest
```
