### ISSUE TITLE
install dive in alpine container

### ISSUE THREAD

**Issue by mlarcher** [wagoodman/dive#312]
Is there any way to have `dive` run in an Alpine container ?
It is not listed as installable through apk, and I can't get the go version to work (`/bin/sh: dive: not found` after installing through `go get`).
Sorry to be asking a support question in here, I just find it odd that a tool focusing on image performance would not work in a performant image

**Comment by wagoodman** [comment]
All good!

Dive is already distributed in an alpine image on [dockerhub] (https://registry.hub.docker.com/r/wagoodman/dive) : `docker pull wagoodman/dive`

If you're looking to package it yourself then checkout the Dockerfile in the [root of the repo](https://github.com/wagoodman/dive/blob/master/Dockerfile) as a starting point --for the `copy` command you can download the [pre-built asset](https://github.com/wagoodman/dive/releases/tag/v0.9.2).

**Comment by mlarcher** [comment]
Thank you @wagoodman , the pre-built assets were what I needed :+1:
