### ISSUE TITLE
Dive flags directory copied in multi-stage build as wasted bytes

### ISSUE THREAD

**Issue by artis3n** [wagoodman/dive#316]
When I build a container in a single image that compiles an app into `/app`, `dive` rightfully considers `/app` important and doesn't list that content as inefficient or wastedBytes.

However, when I move this Dockerfile into a multi-stage build and `COPY --from=0 /app /app`, `dive` considers the `/app` directory as wasted bytes. Is there a way to explicitly tell dive to consider this directory important?

Reproduce:

```bash
git clone https://github.com/artis3n/pgmodeler-container.git
git submodule init && git submodule update --remote
# main branch with a single image in the Dockerfile
git checkout a088ea69ad3c806088418889faf6c8dac6bd107a
# Build the container, will take about 25 minutes
docker build . -t artis3n/pgmodeler:test
# Test the image
dive artis3n/pgmodeler:test
# Observe /app is not considered wasted bytes

# Now, try with the multi-stage build

# commit with the multi-stage build
git checkout 8dc5f5005692adf287ea624d4eae7805ea60ab72
# Build the container, will take about 25 minutes (quick if the first layer is cached from the previous build)
docker build . -t artis3n/pgmodeler:test
# Test the image
dive artis3n/pgmodeler:test
# Observe /app is wasted bytes
```

Single image:
![image](https://user-images.githubusercontent.com/6969296/93010116-d8b5b100-f556-11ea-87b0-d208d305f4ee.png)

Multi-stage:
![image](https://user-images.githubusercontent.com/6969296/93009805-4eb81900-f553-11ea-8d3f-fe0c83202bde.png)

**Comment by wagoodman** [comment]
Thanks for the instructions! There is not a way to ignore paths, and previous stages in the multi stage build should not be included in the analysis. 

In the specific case here the duplicate path is not due to the `COPY` instruction, but instead the [`chown` command](https://github.com/artis3n/pgmodeler-container/blob/main/Dockerfile#L62) is causing the `/app` directory contents to be copied up to the current layer.

If you modify:
```Dockerfile
COPY --from=compiler /app /app

# Set up non-root user
RUN groupadd -g 1000 modeler \
    && useradd -m -u 1000 -g modeler modeler \
    && chown -R modeler:modeler /app
```
To:
```Dockerfile
# Set up non-root user
RUN groupadd -g 1000 modeler \
    && useradd -m -u 1000 -g modeler modeler

COPY --chown modeler:modeler --from=compiler /app /app
```
... you should be good to go, and get 17-ish MB back :) .

**Comment by artis3n** [comment]
:O

TIL about `--chown`. That's great, thanks.
