### ISSUE TITLE
How to see all layers?

### ISSUE THREAD

**Issue by caleb15** [wagoodman/dive#328]
This is probably just me missing something obvious but with a image that has so many layers that it doesn't fit in the screen, the last few layers are not shown and I don't know how to get to them. I tried pressing the down arrow and page down and nothing happened.

![image](https://user-images.githubusercontent.com/46505081/100174485-6419bf80-2e81-11eb-8001-0d33d076e36f.png)

![image](https://user-images.githubusercontent.com/46505081/100174526-7267db80-2e81-11eb-82a9-1d001e56f952.png)

As you can see in the image above there are more layers not displayed. Note that the image immediately above shows layers in reverse order (first layer at bottom, last layer on top)

**Comment by mjlescano** [comment]
Hi! I'm having the same problem, maybe it is worth noting that my image is on a private repo and uses a multi stage build?

**Comment by wagoodman** [comment]
Fixed in https://github.com/wagoodman/dive/pull/399

**Comment by stephanschielke** [comment]
> Hi! I'm having the same problem, maybe it is worth noting that my image is on a private repo and uses a multi stage build?

_Sorry for bumping, but I ran into the same issue for multi-stage builds and hope this helps the next person:_

```
docker history image_name:latest
```
will only show/contain the layers of the last stage in your multi-stage build. 
Therefore, `dive` can't analyse them.

If you want to see the layers of your previous stages, you have to build a specific image up to a target stage:

```
docker build --target stage_name -t image_name:stage_name .
dive image_name:stage_name
```
