### ISSUE TITLE
newer version

### ISSUE THREAD

**Issue by 030** [wagoodman/dive#366]
Could you update protobuf and release a newer version of dive?

**Comment by 030** [comment]
@abitrolly What is the equivalent of dive in that organization?

**Comment by abitrolly** [comment]
I don't think there are tools for interactive introspection. Tools for automated image scanning.

**Comment by 030** [comment]
https://github.com/030/dive

**Comment by 030** [comment]
@wagoodman I would like to contribute. Could you please let me know this week if that is possible? We use the tool in several environments and the tool needs security updates. I have updated the fork, would like to create a PR and would like to use a newer version of this tool.

**Comment by 030** [comment]
@wagoodman Could you review the PR, merge it and release v0.10.1?
