### ISSUE TITLE
Update documentation for Windows "go get" -> "go install"

### ISSUE THREAD

**Issue by mdeweerd** [wagoodman/dive#378]
I got a message when installing using `go get` on windows:

> go get: installing executables with 'go get' in module mode is deprecated.
>         Use 'go install pkg@version' instead.
>         For more information, see https://golang.org/doc/go-get-install-deprecation
>         or run 'go help get' or 'go help install'.

So it says that we should use `go install` .  And a version needs to be add '@latest' will do.

So it becomes:
```
go install github.com/wagoodman/dive@latest
```

But then:
```
go install: github.com/wagoodman/dive@latest (in github.com/wagoodman/dive@v0.10.0):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

So apparently more than just a documentation update.

This could be a different issue, but I guess it is related.
it seemd that another fix is needed as well, I also get:
> # github.com/wagoodman/dive/dive/image/docker
> go\pkg\mod\github.com\wagoodman\dive@v0.10.0\dive\image\docker\engine_resolver.go:53:19: undefined: client.Opt
> go\pkg\mod\github.com\wagoodman\dive@v0.10.0\dive\image\docker\engine_resolver.go:81:34: undefined: client.WithAPIVersionNegotiation

My version:
> go version go1.17.3 windows/amd64

**Comment by saisrivathsa** [comment]
Facing the same issue on go 1.18

**Comment by mnaser** [comment]
Duplicate of #355

**Comment by mdeweerd** [comment]
Stale, closing (limiting my issue backlog).  And claimed to be a duplicate.
