### ISSUE TITLE
Missing maintainer in Debian source package control files

### ISSUE THREAD

**Issue by d4nyll** [wagoodman/dive#38]
Your source package control files [should include the `Maintainer` field](https://www.debian.org/doc/debian-policy/ch-controlfields.html). Otherwise `dpkg` complains:

```
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 40464 package 'dive':
 missing maintainer
```

**Comment by wagoodman** [comment]
Added in 3f12f9dd77cedd77f09efb740e8f2a88e949ad8d
