### ISSUE TITLE
Love the tool, great effort; please use SemVer.

### ISSUE THREAD

**Issue by davidjeddy** [wagoodman/dive#419]
Love the work your doing here. Really good tool, great effort. Please use SemVer 2 versioning. This is the only tool of a dozen or so that has a special version syntax and adds un-needed complexity to automation and pipeline logic.

v0.10 would be 0.10.0 for example

https://semver.org/

**Comment by 030** [comment]
@davidjeddy Could you indicate where you see the 0.10? I see v0.10.0 in the releases.

**Comment by wagoodman** [comment]
I think you might have seen this in the docker tag: https://hub.docker.com/layers/wagoodman/dive/v0.10/images/sha256-99f1f4aa52ad34310766a53076a6d272be23335febf43ef9c33838f2f2ba481b?context=repo

which is an alias for `0.10.x`... the full version is still published: https://hub.docker.com/layers/wagoodman/dive/v0.10.0/images/sha256-99f1f4aa52ad34310766a53076a6d272be23335febf43ef9c33838f2f2ba481b?context=repo
