### ISSUE TITLE
wget return 302

### ISSUE THREAD

**Issue by tochitopor** [wagoodman/dive#427]
wget https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.deb
--2023-01-26 11:57:41--  https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.deb
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found

**Comment by mark2185** [comment]
Latest version is `v.0.10.0` tho

**Comment by tochitopor** [comment]
same thing

wget https://github.com/wagoodman/dive/releases/download/v0.10.0/dive_0.10.0_linux_amd64.deb
sudo apt install ./dive_0.10.0_linux_amd64.deb
--2023-01-26 12:15:23--  https://github.com/wagoodman/dive/releases/download/v0.10.0/dive_0.10.0_linux_amd64.deb
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found

**Comment by mark2185** [comment]
No idea, tried it in a `ubuntu` container and it completed successfully.

Does `wget` download the file?

**Comment by tochitopor** [comment]
dive_0.10.0_linux_amd64.deb.4                     0%[                                                                                                        ]       0  --.-KB/s    in 0s

**Comment by mark2185** [comment]
Alright, so it's a networking issue. 

Are you behind a VPN, or in a country that has internet limitations or something of sorts?

Can you `wget` anything off of the internet?

**Comment by tochitopor** [comment]
You are right. I can't download anything.
I use virtual box. Could it be because of this?

**Comment by mark2185** [comment]
Could be. 

Do you have internet access inside the machine at all?

In any case, it's not a `dive` issue.

**Comment by tochitopor** [comment]
I have internet. I can clone this project, for example.
Thanx. I close issue and resolve this problem.
