### ISSUE TITLE
Discontinued? 

### ISSUE THREAD

**Issue by krstp** [wagoodman/dive#444]
After long pause in using `dive` I wanted to use it:
`dive <image>:<tag>`

and here is what I get:
```
Image Source: docker://<image>:<tag>
Fetching image... (this can take a while for large images)
Handler not available locally. Trying to pull '<image>:<tag>'...
<tag>: Pulling from <image_path>
Digest: sha256:<...>
Status: Image is up to date for <image>:<tag>
<image>:<tag>
cannot fetch image
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Note the `docker` is running as at roughly the same time I am building some other image and pushing. So... not sure what's going on? Wrong docker pointer within `dive`? 🤔 

Help would be appreciated. Thanks!

**Comment by cande1gut** [comment]
@krstp This doesn't sound like dive is the problem. Did you try using it with another image? I recently downloaded the latest version and is working for me.

**Comment by krstp** [comment]
Thanks for the input and verification. Found this particular answer that helped: https://stackoverflow.com/questions/44084846/cannot-connect-to-the-docker-daemon-on-macos/74148162#74148162

In short, define:
```
export DOCKER_HOST=unix:///Users/$(whoami)/Library/Containers/com.docker.docker/Data/docker.raw.sock
```
which can become part of `.zshrc` if that's the preferred shell.
