### ISSUE TITLE
Newly added content does not show dir content size

### ISSUE THREAD

**Issue by wagoodman** [wagoodman/dive#45]
```
Permission    UID:GID       Size  Filetree
drwxr-xr-x        0:0      33 kB  └── usr
drwxrwxr-x       0:50      33 kB      └── local
drwxrwxr-x       0:50      33 kB          └── lib
drwxr-xr-x       0:50      33 kB              └── python3.6
drwxr-xr-x       0:50      33 kB                  └── site-packages
----------        0:0        0 B                      └── pip    <--- should be 33 kB
----------        0:0        0 B                          └── _vendor    <--- should be 33 kB
----------        0:0        0 B                              └── webencodings    <--- should be 33 kB
-rw-r--r--       0:50      11 kB                                  ├── __init__.py
drwxr-xr-x       0:50        0 B                                  ├── __pycache__
-rw-r--r--       0:50     9.2 kB                                  ├── labels.py
-rw-r--r--       0:50     1.4 kB                                  ├── mklabels.py
-rw-r--r--       0:50     6.7 kB                                  ├── tests.py
-rw-r--r--       0:50     4.6 kB                                  └── x_user_defined.py
```

Reproduce: on layer `sha256:af42f63b41404741ab` in image `amir20/clashleaders:latest`

**Comment by TJM** [comment]
Also look at #49 .. in addition to the sizes being wrong, the "color" should be green (added) rather than "yellow" (modified) for new directories. 

On a side note, I am interested in this amir20/clashleaders image, but OpenDNS is blocking it from here :p  (even on GuestWiFi, guh)

**Comment by wagoodman** [comment]
Nice find on the color mismatches. Indeed there are a few problems here:

1. we are modifying trees as we compare them, so to ensure that nested additions are marked properly all comparisons should be done against a copy of the tree.
2. calculating directory sizes should account for the fact if that directory is removed or not. That is, removed files within a removed directory should be included in sizes (to show a negative change in size) but removed files in non-removed directories should not be considered in the parent directories contained size.
3. Apparently the TarHeader doesn't always mark regular files vs directories based on what I can tell... so changing the test against "how many children does this node have" is the next best thing to detect if this node is a directory.

Accounting for all of these fixes the size and color issues you described, @TJM.
