### ISSUE TITLE
0.10.1 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [wagoodman/dive#456]
👋 it looks like 0.10.1 release was not completed, see [this action run](https://github.com/wagoodman/dive/actions/runs/5465690573), raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/135857

**Comment by abitrolly** [comment]
Yes, the tag needs to be moved to abbac157bbf52053e603d569483b17b1f1f49293. The build for that also fails, but this time most likely because CircleCI deploy key is expired https://app.circleci.com/pipelines/github/wagoodman/dive/487/workflows/6f702890-b761-482e-b27a-b9d8a50c747e/jobs/1409

**Comment by wagoodman** [comment]
indeed! It's been a while since I released this 😳  I'm going to rework the pipeline and roll forward to the next release (`v0.11.0` that has several more additions) instead of fixing the current release.

**Comment by chenrui333** [comment]
Sounds good 👍

**Comment by wagoodman** [comment]
v0.11.0 has been released 🎉 (took a little longer since I felt the need to rewrite the release pipeline) shout out if you see any more problems!
