### ISSUE TITLE
Feature Request: Arrow keys to collapse and expand directories

### ISSUE THREAD

**Issue by DomHudson** [wagoodman/dive#46]
This is a very cool project - I appreciate the work. I've just got a minor feature request/suggestion. To me it feels quite natural to close directories with the left arrow key and open them with the right. 
What do you think?

**Comment by akshaychhajed** [comment]
Just to maintain symmetry 😉, I will try.

**Comment by DomHudson** [comment]
One option would be to have the left key close the directory if your cursor is currently on a directory, otherwise go back to the parent folder. This way pressing left once will jump to the parent, pressing again would close it and repeat. You could keep pressing left and it would iteratively jump higher and close the directories.

**Comment by TJM** [comment]
I was thinking something like "shift+left-arrow" if you want to navigate left, but leave it expanded?

**Comment by wagoodman** [comment]
@DomHudson , your suggestion is tempting, but I feel that a file explorer expanding a dir on navigation makes sense, but closing on navigation is an extra mental leap. That is, usually the user is trying to see more content more quickly, not hide it more quickly. 

However, I agree that there is room for improvement to make the file explorer more intuitive and in general add more user-friendly features... even a simple search to jump a user to a matching file/path.

**Comment by DomHudson** [comment]
Thank you very much for the quick turnaround!
