### ISSUE TITLE
Can we do docker layer wise scan for vulnerability detection

### ISSUE THREAD

**Issue by suhalvemu** [wagoodman/dive#465]
**What would you like to be added**:
   At each layer if there any vulnerabilities present at the time of scanning we can show/display the CVE ID's for better vulnerability detection

**Why is this needed**:
   It gives the health of image  and helps us with better information in vulnerability scanning.
**Additional context**:

**Comment by ecki** [comment]
hm, dont think dive has a CVE scanner?
Anyway, what you ask for is implemented in trivy and docker scout.

**Comment by suhalvemu** [comment]
Actually Trivy does not support layer wise scanning. I am not sure about docker scout. But since we are able to show what is present in layers of docker, can we integrate trivy and provide a feature for showing CVE at each layer.

**Comment by suhalvemu** [comment]
makes sense.
