### ISSUE TITLE
directory size is not calculated past the root level

### ISSUE THREAD

**Issue by TJM** [wagoodman/dive#49]
It appears that the directory sizes are not calculated past the root.

![screen shot 2018-10-29 at 8 29 53 am](https://user-images.githubusercontent.com/1641316/47656699-2b4d7600-db55-11e8-82e8-de7ee2b170f5.png)

Let's ignore the fact that I should have used `--no-cache-dir`, but I think that looks like an inconsistency.

To clarify, I am not sure if /root should show 77MB or 0. I am thinking that there should be an option to show the size that a directory contains, because all directories are "effectively" 0 (or very close to 0).

~tommy

**Comment by TJM** [comment]
Also, for what its worth, the color is probably wrong. from /root/.cache down should have been green?

**Comment by wagoodman** [comment]
I feel like this may be related to #45 .

**Comment by TJM** [comment]
@wagoodman I think you are right, but mine is more colorful, we can close this as a duplicate of #45
