### ISSUE TITLE
Suggestion - change space to "page down"

### ISSUE THREAD

**Issue by TJM** [wagoodman/dive#50]
Thanks to @akshaychhajed for writing the left/right "arrow stuff" !

Another recommendation, is that in the "xxx Layer Contents" view, "space" should be used as a "page down" key, similar to using "less" or "more" to page through the contents of a file. I am not sure what other file browsing interface makes me think to use space to scroll down, so I will stick with less/more. I suppose you could enable "page up" and "page down" while you are at it, but space feels more natural for some reason, at least to me. :)

This may require a slight adjustment to the "left arrow" UI that was merged over the weekend, such that if you hit left arrow on an expanded directory, it will compress it,  if it is already compressed, you will move up to the parent directory. If this is too complex (overloading the left arrow too much), maybe we could select a different modifier?

~tommy

**Comment by TJM** [comment]
Actually, I am primarily suggesting using "Space" as a "Page Down" ... which would necessitate "2" above. I don't actually have "physical" page-up or page-down keys on my laptop, but think it would be logical for them to work, if you write the function to handle "space" as page-down, you could also bind the physical page-down key to it.

**Comment by akshaychhajed** [comment]
From what I saw in "less" keybindings, it uses f for PgDn and b for PgUp.
Yes, we could always add more keybindings for the feature.
Let me see if I can get the feature in.
We could always discuss which keys to assign for them.

**Comment by wagoodman** [comment]
@TJM I think adding a page up/down feature to the file tree would be great. However, the most intuitive keys would be the PgUp and PgDn keys. Typically the "space" keybinding for an application that pages only allows one direction, where here we should be allowing for two directions (maybe shift+space? but I haven't seen precedence for that).

Though, I just opened up #51 (based on your comment in #41) which would allow you to override any keybinding... which means you'd be able to remap pagination and toggle collapse as you wish (the only thing you wouldn't be able to do is collapse on navigate).

**Comment by TJM** [comment]
The problem is there are soo many tools out there, and it depends on which ones you commonly use as to which shortcut keys are "natural" to you. If the PageUp/PageDn capability exists, mapping space to engage pagedn should be simple, as you have noted. :)

Thanks!
Tommy
