### ISSUE TITLE
Failure due to missing layers

### ISSUE THREAD

**Issue by markusheiden** [wagoodman/dive#558]
**What happened**:
Layers could not be found. Even with `-i` dive won't start.

**What you expected to happen**:
No errors.

**How to reproduce it (as minimally and precisely as possible)**:
`dive node:22@sha256:35a5dd72bcac4bce43266408b58a02be6ff0b6098ffa6f5435aeea980a8951d7` on an Apple ARM results in `could not find 'blobs/sha256/f715b6c8c4fffd54af22e15764afcb686f56e2218f7c7325e8093eeb3e7afe24' in parsed layers`.

**Anything else we need to know?**:
I suspect this has to do with node:22 maybe not being available for Apple ARM or the concrete image being an x86 one. Anyway this shouldn't prevent browsing the image's file system.

**Environment**:
- OS version macOS 15.1.1
- Docker version (if applicable) 27.3.1

**Comment by DeanAyalon** [comment]
This seems to be a duplicate of the error appearing in #507, #510, and #534

Try building the tool with #511 merged in
[Joschi's fork](https://github.com/joschi/dive) has a release with it merged in, as well as other fixes, if you'd like to use it

**Comment by markusheiden** [comment]
Yes, I use containerd.

I will try to build the fixed version and report back.

**Comment by markusheiden** [comment]
Joshi's fork works for me. So I am closing this as duplicate.
