### ISSUE TITLE
dive fails in main.go 

### ISSUE THREAD

**Issue by k3ck3c** [wagoodman/dive#58]
Hello

Ubuntu 
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"

I have a big image of nearly 3 GB, it is a Windows freeware + wine + winetricks dotnet40 and some more things

The Dockerfile is here
https://github.com/k3ck3c/docker_captvty/blob/master/Dockerfile

$ dive k3ck3c/captvty
Analyzing Image
  Fetching metadata...
  Fetching image... [========================================>] 853 % (23883187200/2799904704)panic: (*logrus.Entry) (0x9622c0,0xc42030c8a0)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc42008c1e0, 0xc420300a20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/wagoodman/go/src/github.com/sirupsen/logrus/entry.go:138 +0x2d2
github.com/sirupsen/logrus.(*Entry).Panic(0xc42030c840, 0xc4201cb418, 0x1, 0x1)
	/home/wagoodman/go/src/github.com/sirupsen/logrus/entry.go:206 +0xb8
github.com/sirupsen/logrus.(*Logger).Panic(0xc42008c1e0, 0xc4201cb418, 0x1, 0x1)
	/home/wagoodman/go/src/github.com/sirupsen/logrus/logger.go:245 +0x6d
github.com/sirupsen/logrus.Panic(0xc4201cb418, 0x1, 0x1)
	/home/wagoodman/go/src/github.com/sirupsen/logrus/exported.go:112 +0x4b
github.com/wagoodman/dive/image.saveImage(0x7ffd3590d29f, 0xe, 0x0, 0x0, 0x0, 0x0)
	/home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:394 +0x7f9
github.com/wagoodman/dive/image.InitializeData(0x7ffd3590d29f, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/wagoodman/go/src/github.com/wagoodman/dive/image/image.go:216 +0x218
github.com/wagoodman/dive/cmd.analyze(0xc49040, 0xc4202adbe0, 0x1, 0x1)
	/home/wagoodman/go/src/github.com/wagoodman/dive/cmd/analyze.go:36 +0x119
github.com/spf13/cobra.(*Command).execute(0xc49040, 0xc42000c090, 0x1, 0x1, 0xc49040, 0xc42000c090)
	/home/wagoodman/go/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc49040, 0x2, 0x7f6a6a6e6000, 0x0)
	/home/wagoodman/go/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0xc49040, 0xc4201cbf78, 0xc4201cbf58)
	/home/wagoodman/go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/wagoodman/dive/cmd.Execute()
	/home/wagoodman/go/src/github.com/wagoodman/dive/cmd/root.go:29 +0x2d
main.main()
	/home/wagoodman/go/src/github.com/wagoodman/dive/main.go:38 +0xad
$ 

Strangely a similar docker image works fine, the V3 of captvty needs dotnet45 instead of dotnet40

$ dive k3ck3c/captvty_v3_1
Analyzing Image
  Fetching metadata...
  Fetching image... [========================================>] 100 % (1773129474/1773129474)
  Discovering layers... Done!
    ├─ d9ae5c1d4ac6bbd : [========================================>] 100 % (1391/1391)
    ├─ c0f54c265c37cfb : [========================================>] 100 % (0/0)
    ├─ bc3ec266020bec7 : [========================================>] 100 % (0/0)
    ├─ b1e009a6319c746 : [========================================>] 100 % (11887/11887)
    ├─ b1d1ef38fb95e3a : [========================================>] 100 % (28053/28053)
    ├─ af1698304b91f01 : [========================================>] 100 % (406/406)
    ├─ aa8bc6812fde7c4 : [========================================>] 100 % (2/2)
    ├─ a1291ad504ea07a : [========================================>] 100 % (411/411)
    ├─ 93f482e26b90949 : [========================================>] 100 % (109/109)
    ├─ 8ca9149dc6380dd : [========================================>] 100 % (1417/1417)
    ├─ 847197a4314af40 : [========================================>] 100 % (91/91)
    ├─ 77a9ca4ab4bf912 : [========================================>] 100 % (27/27)
    ├─ 7635b529d1a8393 : [========================================>] 100 % (459/459)
    ├─ 6cf6f9e81ab6e22 : [========================================>] 100 % (2700/2700)
    ├─ 6caf6ffc40ea242 : [========================================>] 100 % (0/0)
    ├─ 5e17bbbd3b0b9aa : [========================================>] 100 % (0/0)
    ├─ 5d68c61bc5a325b : [========================================>] 100 % (8022/8022)
    ├─ 5b68def4cd8a4d6 : [========================================>] 100 % (21/21)
    ├─ 4df713f6b293fe7 : [========================================>] 100 % (1118/1118)
    ├─ 45c72127698e9ca : [========================================>] 100 % (65/65)
    ├─ 4320f0f8b4d99d7 : [========================================>] 100 % (243/243)
    ├─ 3d23ed2956a6bd6 : [========================================>] 100 % (27/27)
    ├─ 3c592c31236d218 : [========================================>] 100 % (3/3)
    ├─ 342f6081907bb97 : [========================================>] 100 % (6/6)
    ├─ 296a0569b4ccc98 : [========================================>] 100 % (66/66)
    ├─ 27fc70269f0ce32 : [========================================>] 100 % (22/22)
    ├─ 20e995179a014c0 : [========================================>] 100 % (25147/25147)
    ├─ 13394172ac14e25 : [========================================>] 100 % (19/19)
    ├─ 08859828a9e2224 : [========================================>] 100 % (89/89)
    ├─ 05eeb36077397ff : [========================================>] 100 % (2257/2257)
  Fetching image config...
  Building tree...
  Analyzing layers...
$

The Dockerfile of Captvty V3 

FROM ubuntu:16.04
ENV DEBIAN_FRONTEND noninteractive
ENV LANG fr_FR.UTF-8
ENV LANGUAGE fr_FR:en
ENV LC_ALL fr_FR.UTF-8
# activate i386 arch for Wine and install stuff we need
RUN locale-gen fr_FR.UTF-8 && \
dpkg --add-architecture i386 && \
	apt-get update && \
        BUILD_PACKAGES='wget software-properties-common unzip apt-transport-https openssh-server xauth cabextract winbind squashfs-tools pulseaudio x11-apps xfce4 cups joe xfce4-terminal xvfb socat x11vnc' &&\
	apt-get -qy upgrade && apt-get -qy install $BUILD_PACKAGES && \
        AUTO_ADDED_PACKAGES=`apt-mark showauto` && \	
	# install latest Wine
	wget -qO- https://dl.winehq.org/wine-builds/Release.key | apt-key add - && \
	apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/ && \
	apt-get update && apt-get -qy install --no-install-recommends winehq-devel && \

	# make sshd work and enable X11 forwarding
	# create our user for Wine
useradd -d /home/gg -m -s /bin/bash gg && \
echo gg:gg | chpasswd && \ 
	wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks -O /tmp/winetricks && \
	chmod +x /tmp/winetricks && \
echo $AUTO_ADDED_PACKAGES && \
sleep 11
        USER gg 
ENV WINEDEBUG=-all WINEPREFIX=/home/gg/.wine WINEARCH=win32
RUN winecfg && \
xvfb-run -a /tmp/winetricks -q --unattended dotnet45 corefonts comctl32 gdiplus vcrun2010 ie8
        USER root	
	# cleaning up
	RUN apt-get autoremove -y --purge software-properties-common && \
	apt-get autoremove -y --purge && \
	apt-get remove --purge -y software-properties-common apt-transport-https openssh-server xauth cabextract winbind squashfs-tools pulseaudio x11-apps xfce4 cups joe xfce4-terminal xvfb socat x11vnc && \
	apt-get clean -y && \
	rm -rf /home/wine/.cache && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /tmp/inetricks
USER gg
RUN wget -q -O- http://v3.captvty.fr/ | egrep -o '\/\/.+?\.zip' | sed 's/\/\//http:\/\//' | xargs wget -O /tmp/v3Captvty.zip && \
ls -alrt /tmp/v3Cap*zip && unzip -d  ~/Captvtyv3 /tmp/v3Captvty.zip && rm /tmp/v3Captvty.zip 
USER root
RUN apt-get remove --purge -y wget &&\
        apt-get clean -y && \
	apt-get autoremove -y && \
	rm -rf /home/wine/.cache && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
USER gg
CMD wine /home/gg/Captvtyv3/Captvty.exe

You can get Captvty.exe from 
http://captvty.fr/

and the V3 of Captvty
from
http://v3.captvty.fr/ 

Thanks for your work!

**Comment by wagoodman** [comment]
I can give that a shot, what version of dive did you use?

**Comment by k3ck3c** [comment]
dive 0.0.8

I guess it is the latest (pip installed yesterday)

**Comment by k3ck3c** [comment]
well on another computer running Debian 9 instead if Ubuntu, it works fine, so I guess something is wrong on my Ubuntu computer

**Comment by wagoodman** [comment]
@k3ck3c I haven't been able to reproduce this, however the left over temp dir on crash is bad! I've fixed that issue and it should make it in the v0.3.0 release. I'll close this for now, though if you run into this problem again feel free to open another issue and add any additional info.

**Comment by k3ck3c** [comment]
thanks for your time!

I guess I will not use much this version 2.7.8 of Captvty as the author
recommends moving to the V3, which worked fine with dive.



Le dim. 25 nov. 2018 à 03:04, Alex Goodman <notifications@github.com> a
écrit :
