### ISSUE TITLE
Use dive with docker-machine on Mac?

### ISSUE THREAD

**Issue by miketitus** [wagoodman/dive#59]
The `dive` install instructions include the option for installing `dive` to a Mac using brew.  However, it's not apparent if there's anyway to use `dive` with `docker-machine` on a Mac.
```
$ docker-machine ls
NAME      ACTIVE   DRIVER   STATE     URL                       SWARM   DOCKER        ERRORS
default   *        xhyve    Running   tcp://192.168.64.2:2376           v18.06.1-ce
$ dive busybox
Analyzing Image
Using default tag: latest
latest: Pulling from library/busybox
Digest: sha256:2a03a6059f21e150ae84b0973863609494aad70f0a80eaeb64bddd8d92465812
Status: Image is up to date for busybox:latest
  Fetching metadata...
  Fetching image...panic: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
It's clear _why_ this error is happening: docker-machine doesn't open a socket in /var/run.  Is there any workaround for this?  Thanks.

**Comment by wagoodman** [comment]
The latest v0.1.0 of dive should respond to the DOCKER_HOST env var, allowing connections to remote docker daemons. 

Let me know how it goes!

**Comment by miketitus** [comment]
I ran `brew upgrade dive` and it upgraded from 0.0.8 to 0.1.0 and now it works correctly.  Thank you!
