### ISSUE TITLE
Please use $XDG_CONFIG_HOME for config storage

### ISSUE THREAD

**Issue by z0rc** [wagoodman/dive#60]
https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html is more than a decade old, nowadays it isn't acceptable to put config dotfiles in `$HOME`. Majority of CLI applications follow it: systemd, mc, git, htop...

Please switch config path to `$XDG_CONFIG_HOME/dive.yaml`, with fallback to `$HOME/.config/dive.yaml`, if the var isn't set.

**Comment by wagoodman** [comment]
Agreed, though it makes sense to continue to allow for `$HOME/.dive.yaml` since folks are already dependent on it.

**Comment by dsifford** [comment]
Can support for the actual spec be implemented? 

XDG does not allow for putting configuration files directly in the `~/.config` directory. Instead, it should be `~/.config/dive/config.yml`, with the `config.yml` part being named whatever you like (e.g. `dive.yml`, `config.yml`, etc).

Thanks for considering.
