### ISSUE TITLE
🙏 give a way to squash layers

### ISSUE THREAD

**Issue by mathieu-pousse** [wagoodman/dive#65]
Hi, 

As you seem to be mastering the docker layers, could you please give a way to squash multiple layers together.

Sometimes, docker images contains a layer with dozen of files removed on another layers.

Thanks in advance

**Comment by wagoodman** [comment]
I've considered this before (https://github.com/wagoodman/dive/projects/1#card-10593749) but haven't convinced myself to add image modification features. Currently this is a "read only" tool for exploring your image, modifying it would be outside of scope.

Though, docker does support (experimentally) squashing an image: https://docs.docker.com/engine/reference/commandline/image_build/#options (note the `--squash` option). You can compare the differences by comparing the output of `dive build -t your-image-tag .` and `dive build -t your-image-tag --squash .` to see the result.
