### ISSUE TITLE
RFE - Add an option to collapse all dirs

### ISSUE THREAD

**Issue by delabassee** [wagoodman/dive#70]
By default, all directories are uncollapsed.
Adding an option to collapse all directories would allow to easily spot layer's diff (combined with the `^L  Show layer changes` option) without having to manually collapse all directories.

**Comment by wagoodman** [comment]
This is now configurable via `filetree.collapse-dir` (the readme has been updated to reflect this). It'll be out in the next 0.3.0 release.
