### ISSUE TITLE
Unable to view layers below the fold in the layer list

### ISSUE THREAD

**Issue by ulrikjohansson** [wagoodman/dive#72]
I just noticed that I'm unable to view the bottom layers of an image with more layers than can fit in the layer list without scrolling. This is on a Centos7 machine.

Workaround seems to be to up the screen resolution so more layers fit in the window =)
That is how I got around it temporarily.

**Comment by wagoodman** [comment]
Screen real estate is indeed a challenge with this app... can you post a screenshot for clarity?

**Comment by ulrikjohansson** [comment]
I see now that my description of my problem was a bit ambiguous. It's not a problem with the amount of stuff I can see at any one time, it's that the layer list doesn't scroll for me, so I can't select layers below the "fold". With a bigger screen I solved it temporarily because a few more layers showed up in the list.

**Comment by ulrikjohansson** [comment]
Awesome tool by the way, really helpful for troubleshooting image builds. 👍😀

**Comment by wagoodman** [comment]
thanks @ulrikjohansson ! I haven't been able to reproduce this, that is, regardless of the number of layers or terminal size, the layer view always scrolls from the first layer to the last layer without issue. Can you give more info? 

1. what version of dive are you using?
2. if the image is public, can you provide the image name/url? if it is not public, how many layers are in the image you are seeing issues with?

**Comment by ulrikjohansson** [comment]
I can't reproduce this anymore, I'm using 0.5.0 now.
I guess it was either some weird local glitch in combination with an earlier version (I think I was using 0.2.0 but might have been earlier than that as well), or my eyes were deceiving me. I'm closing this, as no one else seems to have stumbled on anything like this either.

Thanks for taking the time to follow up!
