### ISSUE TITLE
Make CI friendly

### ISSUE THREAD

**Issue by wagoodman** [wagoodman/dive#74]
A fun use case would be to use this tool as a static analysis tool in a CI pipeline. When running dive against a built image, dive would pass/fail (return 0 or non-0) with configurable thresholds for efficiency score and/or waisted image space. 

This implies disabling the UI and only output minimal information.

**Comment by wagoodman** [comment]
Implementing #93 along with an exit code would probably be sufficient

**Comment by sbonami** [comment]
I could see output formatters (like [ESLint](https://eslint.org/docs/user-guide/formatters/#checkstyle) or [Jest](https://jestjs.io/docs/en/configuration#coveragereporters-array-string)) as a great extensible solution. Those recognized formats play very well with modern CI tools
