### ISSUE TITLE
DOCKER_HOST without protocol

### ISSUE THREAD

**Issue by gamma** [wagoodman/dive#84]
Docker accepts DOCKER_HOST env without a protocol, falling back to tcp afaik.

It'd be great to support the fallback scenario.

**Comment by wagoodman** [comment]
After further thought assuming a protocol could be problematic. From the documentation it appears that DOCKER_HOST should always specify a protocol (https://docs.docker.com/engine/reference/commandline/dockerd/#examples).

**Comment by mb555444** [comment]
There is another issue I just stumbled across. dive seems to assume port 80 when no port is specified. It should instead assume port 2375.
