### ISSUE TITLE
Building from source fails

### ISSUE THREAD

**Issue by lloeki** [wagoodman/dive#86]
```
$ make build
go build -o build/dive
# github.com/wagoodman/dive/image
image/image.go:205:23: undefined: client.NewClientWithOpts
image/image.go:205:48: undefined: client.FromEnv
image/image.go:338:23: undefined: client.NewClientWithOpts
image/image.go:338:48: undefined: client.WithVersion
image/image.go:338:83: undefined: client.FromEnv
make: *** [build] Error 2
```

Seems like there's a version mismatch since e.g. `client.NewClientWithOpts` doesn't exist in `github.com/docker/docker/client/client.go`, whereas it exists in `https://github.com/moby/moby/client/client.go`. This may come from the `docker` to `moby` rename since the last version of `github.com/docker/docker` is `v1.13.1`. In that case it might be a good thing to move to `github.com/moby/moby`.

**Comment by wagoodman** [comment]
I ran into this issue when attempting to add a go.mod. The issue isn't the docker > moby rename (I also tried locking down to moby/moby with no luck). Dive is dependent on master of the docker repo, but when I attempted to lock down to that commit sha on master, other dependencies broke. Once I bootstrap the right versions for docker dependencies it should be a solved problem, but for the meantime I've had to rely on building with a GOPATH. Did you try building with GOPATH or without?

**Comment by lloeki** [comment]
Without, but since I'm trying to package `dive` for [Arch Mac](https://archmac.org) I'd rather have it work proper instead of using nasty `GOPATH` hacks during package building.

> The issue isn't the docker > moby rename

My bad, it was a shot in the dark and I confirmed that on my side too.

I managed to build it by locking both of those to their respective `master` as of this day:

```
	github.com/docker/distribution v0.0.0-20181126153310-93e082742a009850ac46962150b2f652a822c5ff // indirect
	github.com/docker/docker v0.0.0-20181126153310-0b7cb16dde4a20d024c7be59801d63bcfd18611b
```

Here is the initialisation sequence I used

```
go mod init github.com/wagoodman/dive
go mod vendor  # makes go mod populate go.mod by analysing source code
sed -i~ -e 's#github.com/docker/docker [^ ]*#github.com/docker/docker v0.0.0-20181126153310-0b7cb16dde4a20d024c7be59801d63bcfd18611b#' go.mod
sed -i~ -e 's#github.com/docker/distribution [^ ]*#github.com/docker/distribution v0.0.0-20181126153310-93e082742a009850ac46962150b2f652a822c5ff#' go.mod
go mod vendor  # fetch correct versions
cat go.mod  # check
make build  # success!
```

Should I create a PR with the resulting `go.mod` and `go.sum`?

**Comment by wagoodman** [comment]
Awesome! Thanks for the procedure, always good to know the right way to do it. Feel free to put in a PR, I'll have some time tonight to take a look.

**Comment by lloeki** [comment]
> always good to know the right way to do it

Well TBH the proper way should be:

```
go mod edit -replace=github.com/docker/docker@v1.13.1=github.com/docker/docker@v0.0.0-20181126153310-0b7cb16dde4a20d024c7be59801d63bcfd18611b
```

but for some reason while the terminal output of that command was apparently OK there was no update to the `go.mod` file, so I went for the bulldo`sed` ;)

I'll do the PR right away!

**Comment by lloeki** [comment]
By the way, `dive` is now available on Arch Mac's [extra](https://gitlab.com/archmac/packages/tree/master/extra/dive) repository, so the install is as simple as `pacman -S dive`.

**Comment by mramshaw** [comment]
Interesting, I tried the "go mod edit" approach, the go.mod file looked fine:

====
$ cat go.mod
module github.com/wagoodman/dive

require (
	github.com/Microsoft/go-winio v0.4.11 // indirect
	github.com/docker/distribution v2.6.2+incompatible // indirect
	github.com/docker/docker v1.13.1
	github.com/docker/go-connections v0.4.0 // indirect
	github.com/docker/go-units v0.3.3 // indirect
	github.com/dustin/go-humanize v1.0.0
	github.com/fatih/color v1.7.0
	github.com/google/uuid v1.1.0
	github.com/inconshreveable/mousetrap v1.0.0 // indirect
	github.com/jroimartin/gocui v0.4.0
	github.com/k0kubun/go-ansi v0.0.0-20180517002512-3bf9e2903213
	github.com/lunixbochs/vtclean v0.0.0-20180621232353-2d01aacdc34a
	github.com/mattn/go-colorable v0.0.9 // indirect
	github.com/mattn/go-isatty v0.0.4 // indirect
	github.com/mattn/go-runewidth v0.0.3 // indirect
	github.com/mitchellh/go-homedir v1.0.0
	github.com/nsf/termbox-go v0.0.0-20181027232701-60ab7e3d12ed // indirect
	github.com/phayes/permbits v0.0.0-20180830030258-59f2482cd460
	github.com/pkg/errors v0.8.0 // indirect
	github.com/sirupsen/logrus v1.2.0
	github.com/spf13/cobra v0.0.3
	github.com/spf13/viper v1.2.1
	github.com/wagoodman/jotframe v0.0.0-20181125020952-719d4625b8fa
	golang.org/x/net v0.0.0-20181114220301-adae6a3d119a
)

replace github.com/docker/docker v1.13.1 => github.com/docker/docker v0.0.0-20181126153310-0b7cb16dde4a20d024c7be59801d63bcfd18611b
====

So I ran another "go mod vendor" which seemed to do its' stuff, but the build failed.

The "sed" approach worked fine though.

**Comment by lloeki** [comment]
> So I ran another "go mod vendor" which seemed to do its' stuff, but the build failed.
>
> The "sed" approach worked fine though.

Yeah I've had that too. Super weird.

**Comment by lloeki** [comment]
>  always good to know the right way to do it

@wagoodman FYI here's [a quick rundown](https://www.kablamo.com.au/blog-1/2018/12/10/just-tell-me-how-to-use-go-modules) on how to do things the right way with modules. Notably I used `go mod vendor` twice when I should have been using `go get -u ./...`. The end result is the same though.

**Comment by mramshaw** [comment]
@lloeki Thank you for your guide - although I do think you've over-simplified.
I've wondered why the 'go mod edit' approach did not work, I think the naming may violate SemVer.
For what it's worth, I have a repo about my vgo wrangling: http://github.com/mramshaw/vgo
Russ Cox said at some point that his intention was to keep 'go get' working, so that's something.

**Comment by lloeki** [comment]
> although I do think you've over-simplified.

@mramshaw It's not mine ;) I just stumbled upon it.

Interesting, I'll take a look at your repo.

**Comment by daniel-bryant** [comment]
Commenting bc this is the first google result for "docker undefined: client.NewClientWithOpts" and "docker undefined: client.FromEnv"

I solved this with
```
$ go get github.com/docker/docker@master
$ go get github.com/docker/distribution@master
```
which updated my `go.mod` to:
```
require (
	github.com/docker/distribution v0.0.0-20191024225408-dee21c0394b5 // indirect
	github.com/docker/docker v1.4.2-0.20191113233703-44d39013868a // indirect
)
```
