### ISSUE TITLE
9GB image slows down gnome

### ISSUE THREAD

**Issue by Lorac** [wagoodman/dive#94]
It slows my UI so much that gnome somehow crashes and restart the session. Gnome is slowing down for no apparent reason because the CPU usage is really low (<15) while scanning the image. I have an i7-7700.

**Comment by Lorac** [comment]
I have 32Gb of RAM and  4GB available swap. It's not using much. It's not using any swap. 

It's really hard to monitor use because my UI is getting really choppy. I cannot do much while dive is running on this big image.

I'll test the PR on my side and see if it helps.

**Comment by Lorac** [comment]
Actually, just to be sure I restarted my computer, and the choppiness stopped from gnome, but it took about 19Gb of RAM. 0 swap.

**Comment by wagoodman** [comment]
This is the same as #27 , but we can track the issue here.

**Comment by ChrisCinelli** [comment]
Check #106. With the `do-not-write-image` code the laptop is pretty fast and the memory is low.

When I navigate an image with a lot of files, though, `dive`'s ui is very sluggish. Try with the image `butomo1989/docker-android-x86-9.0`. When you scroll down the layers, you have to eventually wait a few seconds to switch layers. 
The UI code seems to be responsible for this.

**Comment by wagoodman** [comment]
#108 was just merged and fixes this issue (should make it in v0.4.0)
