### ISSUE TITLE
Problem with window resize

### ISSUE THREAD

**Issue by ChrisCinelli** [wagoodman/dive#95]
It I resize the terminal after running `dive`, the output does look messy.

**Comment by wagoodman** [comment]
Indeed, this is actually the same problem in #80 . I've got a fix in the works for it in the supporting library (https://github.com/wagoodman/jotframe which is also in beta)

**Comment by wagoodman** [comment]
Since concurrency is being removed soon, jotframe can be removed, which means this issue should go away. I've created a new issue with jotframe to capture this: https://github.com/wagoodman/jotframe/issues/16

**Comment by wagoodman** [comment]
jotframe was removed in a566ad41f1663a98c2bee3329e219da30d80e42d  (targeting the v0.4.0 release)
