### ISSUE TITLE
go get fails to compile jotframe with go 1.11 on windows/amd64

### ISSUE THREAD

**Issue by leeview** [wagoodman/dive#98]
go version go1.11 windows/amd64

>go build github.com/wagoodman/dive
# github.com/wagoodman/jotframe
github.com\wagoodman\jotframe\signal.go:27:27: not enough arguments in call to syscall.Syscall
github.com\wagoodman\jotframe\signal.go:27:28: undefined: syscall.SYS_IOCTL
github.com\wagoodman\jotframe\signal.go:27:71: undefined: syscall.TIOCGWINSZ
github.com\wagoodman\jotframe\signal.go:33:26: undefined: syscall.SIGWINCH

**Comment by wagoodman** [comment]
Indeed, there are plans to make it truly cross platform (https://github.com/wagoodman/jotframe/issues/13) but it's not there yet. However, a fix that @ChrisCinelli may be putting in soon would remove the concurrent load, which means that jotframe can be removed... which means nothing would be standing in the way from making dive cross platform :)

**Comment by wagoodman** [comment]
Just merged a566ad41f1663a98c2bee3329e219da30d80e42d which removes jotframe. Haven't tried cross compiling yet, but I'll attempt to add a windows build to the next release.

**Comment by leeview** [comment]
thank you for the good work ! cheers
